### ISSUE TITLE
Post an idea button is hard to find

### ISSUE THREAD

**Issue by vishalarora** [r-webdev-projects/joinforces#24]

**Comment by wontoan** [comment]
Current: Have to scroll all the way down to find it.
Suggestion: Move to nav-bar and make it stand out.

**Comment by wontoan** [comment]
Is it just me or does the post an idea button not work unless clicked multiple times?

**Comment by wontoan** [comment]
Field with label "How will this product work? What technology might it use? Who will use it? What problem does it solve for them? How will you monetize?"  is either doing nothing or is the the same as "Start the conversation by asking a question" on the following page.
