### ISSUE TITLE
Missing Commenting functionality

### ISSUE THREAD

**Issue by vishalarora** [r-webdev-projects/joinforces#26]

**Comment by wontoan** [comment]
-Long comments do not wrap. Currently going off screen, requiring user to scroll right.
-Unclear what the heart icon does.
-Reply button is not working

**Comment by vishalarora** [comment]
Wrapping fixed by https://github.com/r-webdev-projects/joinforces/commit/12440a1b5a0192c333a3200c1ed275b4653e130e
